packages:
   - "packages/*"
   - "apps/*"

catalogs:
   react:peer:
      react: ^19.2.6
      react-dom: ^19.2.6
      react-hook-form: ^7.76.1
      tailwind-merge: ^3.6.0
      tailwindcss: ^4.3.0
