import { promises as fs } from "node:fs";
import path from "node:path";
import * as prettier from "prettier";

/**
 * Build script to auto-generate examples/__index__.tsx
 * Scans the examples directory for .tsx files and creates lazy-loaded exports
 */

async function formatGeneratedSource(content: string, filePath: string) {
	const prettierConfig = (await prettier.resolveConfig(path.join(process.cwd(), "package.json"))) ?? {};

	return prettier.format(content, {
		...prettierConfig,
		filepath: filePath,
	});
}

async function buildExamplesIndex() {
	const examplesDir = path.join(process.cwd(), "examples");

	// Read all .tsx files from examples directory
	const allEntries = await fs.readdir(examplesDir, { withFileTypes: true });
	const files = allEntries
		.filter((entry) => entry.isFile() && entry.name.endsWith(".tsx") && entry.name !== "__index.tsx")
		.map((entry) => entry.name)
		.toSorted();

	console.info(`Found ${files.length} example files`);

	// Generate the index file content
	let index = `// This file is autogenerated by scripts/build-examples.mts
// Do not edit this file directly.

import { lazy } from "react";

type ExamplesIndexType = Record<
	string,
	{
		component: React.LazyExoticComponent<() => React.JSX.Element>;
		filePath: string;
		name: string;
	}
>;

export const ExamplesIndex = {`;

	for (const file of files) {
		const name = file.replace(/\.tsx$/, "");

		index += `
	"${name}": {
		component: lazy(() => import("./${name}")),
		filePath: "examples/${file}",
		name: "${name}",
	},`;
	}

	index += `
} satisfies ExamplesIndexType;
`;

	const outputPath = path.join(examplesDir, "__index.tsx");
	const formattedContent = await formatGeneratedSource(index, outputPath);
	await fs.writeFile(outputPath, formattedContent);

	console.info(`✅ Generated ${outputPath}`);
}

try {
	console.info("🏗️ Building examples index...");
	await buildExamplesIndex();
	console.info("✅ Build complete!");
} catch (error) {
	console.error("❌ Build failed:", error);
	// eslint-disable-next-line node/no-process-exit, unicorn/no-process-exit
	process.exit(1);
}
