import { promises as fs } from "node:fs";
import path from "node:path";
import * as prettier from "prettier";

/**
 * Build script to auto-generate examples/__index__.tsx
 * Scans the examples directory for .tsx files and creates lazy-loaded exports
 */

const formatCode = async (content: string, filePath: string) => {
	const prettierConfig = await prettier.resolveConfig(filePath);

	return prettier.format(content, { ...prettierConfig, filepath: filePath });
};

const buildExamplesIndex = async () => {
	const examplesDir = path.join(process.cwd(), "examples");

	const allFileEntries = await fs.readdir(examplesDir, { withFileTypes: true });

	const files = allFileEntries
		.filter((entry) => entry.isFile() && entry.name.endsWith(".tsx") && entry.name !== "__index.tsx")
		.map((entry) => entry.name)
		.toSorted();

	console.info(`Found ${files.length} example files`);

	const stringEntryArray = files.map((file) => {
		const name = file.replace(/\.tsx$/, "");

		return `"${name}": {
		component: lazy(() => import("./${name}")),
		filePath: "examples/${file}",
		name: "${name}",
	},`;
	});

	const stringEntry = stringEntryArray.join("\n");

	const content = `
	// This file is autogenerated by scripts/build-examples.ts
	// Do not edit this file directly.
	import { lazy } from "react";

	type ExamplesIndexType = Record<
		string,
		{
			component: React.LazyExoticComponent<() => React.JSX.Element>;
			filePath: string;
			name: string;
		}
	>;

	export const ExamplesIndex = {
	${stringEntry}
	} satisfies ExamplesIndexType;
`;

	const outputPath = path.join(examplesDir, "__index.tsx");

	await fs.writeFile(outputPath, await formatCode(content, outputPath));

	console.info(`✅ Generated ${outputPath}`);
};

const runScript = async () => {
	try {
		console.info("🏗️ Building examples index...");

		await buildExamplesIndex();

		console.info("✅ Build complete!");
	} catch (error) {
		console.error("❌ Build failed:", error);
		// eslint-disable-next-line node/no-process-exit, unicorn/no-process-exit
		process.exit(1);
	}
};

await runScript();
