// This file is autogenerated by scripts/build-examples.ts
// Do not edit this file directly.
import { lazy } from "react";

type ExamplesIndexType = Record<
	string,
	{
		component: React.LazyExoticComponent<() => React.JSX.Element>;
		filePath: string;
		name: string;
	}
>;

export const ExamplesIndex = {
	"await-demo": {
		component: lazy(() => import("./await-demo")),
		filePath: "examples/await-demo.tsx",
		name: "await-demo",
	},
	"card-demo": {
		component: lazy(() => import("./card-demo")),
		filePath: "examples/card-demo.tsx",
		name: "card-demo",
	},
	"carousel-demo": {
		component: lazy(() => import("./carousel-demo")),
		filePath: "examples/carousel-demo.tsx",
		name: "carousel-demo",
	},
	"client-gate-demo": {
		component: lazy(() => import("./client-gate-demo")),
		filePath: "examples/client-gate-demo.tsx",
		name: "client-gate-demo",
	},
	"drag-scroll-demo": {
		component: lazy(() => import("./drag-scroll-demo")),
		filePath: "examples/drag-scroll-demo.tsx",
		name: "drag-scroll-demo",
	},
	"drop-zone-demo": {
		component: lazy(() => import("./drop-zone-demo")),
		filePath: "examples/drop-zone-demo.tsx",
		name: "drop-zone-demo",
	},
	"error-boundary-demo": {
		component: lazy(() => import("./error-boundary-demo")),
		filePath: "examples/error-boundary-demo.tsx",
		name: "error-boundary-demo",
	},
	"for-demo": {
		component: lazy(() => import("./for-demo")),
		filePath: "examples/for-demo.tsx",
		name: "for-demo",
	},
	"form-demo": {
		component: lazy(() => import("./form-demo")),
		filePath: "examples/form-demo.tsx",
		name: "form-demo",
	},
	"presence-demo": {
		component: lazy(() => import("./presence-demo")),
		filePath: "examples/presence-demo.tsx",
		name: "presence-demo",
	},
	"show-demo": {
		component: lazy(() => import("./show-demo")),
		filePath: "examples/show-demo.tsx",
		name: "show-demo",
	},
	"suspense-with-boundary-demo": {
		component: lazy(() => import("./suspense-with-boundary-demo")),
		filePath: "examples/suspense-with-boundary-demo.tsx",
		name: "suspense-with-boundary-demo",
	},
	"switch-demo": {
		component: lazy(() => import("./switch-demo")),
		filePath: "examples/switch-demo.tsx",
		name: "switch-demo",
	},
	"teleport-demo": {
		component: lazy(() => import("./teleport-demo")),
		filePath: "examples/teleport-demo.tsx",
		name: "teleport-demo",
	},
} satisfies ExamplesIndexType;
