name: Lint and Type

on:
   pull_request:
   push:
      branches: main

permissions:
   contents: read

jobs:
   lint-and-type:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [lts/*]
      steps:
         - name: Checkout code
           uses: actions/checkout@v6

         - name: Setup pnpm
           uses: pnpm/action-setup@v5
           with:
              version: 10.33.0

         - name: Setup Node.js
           uses: actions/setup-node@v6
           with:
              node-version: ${{ matrix.node-version }}
              cache: pnpm

         - name: Install dependencies and build
           run: |
              pnpm install --frozen-lockfile
              pnpm build

         - name: Run linters
           run: |
              pnpm lint:type-check
              pnpm lint:eslint:root
